<?php $old_city = $this->getOldCity(); ?>
<?php $new_city = $this->getNewCity(); ?>
<?php $tax_area_id=$this->getTaxAreaId(); ?>
<div  class="selectaddress-container step a-item" >
    <div lass="col1-set">        
            <h3><?php echo $this->__('Your shipping address has been updated'); ?></h3>          
            <ul class="form-list">
                             
                    <li class="control">                         
                        <label><?php echo $this->__('Original City: %s',ucwords(strtolower($old_city)) ); ?></label>  
                    </li>    
                    <li class="control">                         
                        <label><?php echo $this->__('Validated City: %s',ucwords(strtolower($new_city)) ); ?></label>  
                    </li>                                           
            </ul>
            <div class="buttons-set">
                <p class="required">&nbsp;</p>
                <button onclick="javascript:void(0);" class="button" type="button" id="onepage-select-tax-area-button"><span><span><?php echo $this->__('Continue'); ?></span></span></button>
            </div>    
    </div>
</div>  
  
<script type="text/javascript">
                
    $('opc-selectaddress').style.display = "block";
    $('popup-shadow').style.display = "block";
    $('onepage-select-tax-area-button').observe('click', select_address);
        
    function select_address(){
        var tax_area_id="<?php echo $tax_area_id ?>";
        if (tax_area_id=="undefined" || tax_area_id.length==0) {
            alert('Please change  address');
            return false;
        }
       var new_city="<?php echo $new_city; ?>";
         
        $('opc-selectaddress').style.display = "none";
        $('popup-shadow').style.display = "none"; 
        if ( typeof  shipping !== 'undefined' ) {            
            var success_event=shipping;
            var form_object=$('co-shipping-form');
        }else {            
            var success_event=billing;
            var form_object=$('co-billing-form');
        }
        form_object.innerHTML +='<input id="tax_area_id_el" type="hidden" name="tax_area_id" value="'+tax_area_id+'" />\n\
                                 <input id="tax_new_city_el" type="hidden" name="tax_new_city" value="'+new_city+'" />';
         
 
        var request = new Ajax.Request(
          '<?php echo Mage::getUrl('checkout/onepage/saveTaxArea');?>' ,
            {
               method:'post',
               onComplete: SelectAddressComplete,
               onSuccess: success_event.onSave,                   
               parameters: form_object.serialize(true)
            }
        );  
        console.log(tax_area_id);         
    }    
    
    function SelectAddressComplete(){
        $('tax_area_id_el').remove();       
        $('tax_new_city_el').remove();
        checkout.reloadProgressBlock('billing');
        checkout.reloadProgressBlock('shipping');
        checkout.reloadProgressBlock('shipping_method');
        checkout.reloadProgressBlock('payment_method');       
    }
    
</script>