<?php $old_city = $this->getOldCity(); ?>
<?php $new_city = $this->getNewCity(); ?>
<?php $tax_area_id=$this->getTaxAreaId(); ?>
<div  class="selectaddress-container step a-item" >
    <div lass="col1-set">        
            <h3><?php echo $this->__('Your shipping address has been updated'); ?></h3>          
            <ul class="form-list">
                             
                    <li class="control">                         
                        <label><?php echo $this->__('Original City: %s',ucwords(strtolower($old_city)) ); ?></label>  
                    </li>    
                    <li class="control">                         
                        <label><?php echo $this->__('Validated City: %s',ucwords(strtolower($new_city)) ); ?></label>  
                    </li>                                           
            </ul>
            <div class="buttons-set">
                <p class="required">&nbsp;</p>
                <button onclick="javascript:void(0);" class="button" type="button" id="select-tax-area-button"><span><span><?php echo $this->__('Continue'); ?></span></span></button>
            </div>    
    </div>
</div>  
  
<script type="text/javascript">
    $("popup-shadow").style.height=$("html-body").getHeight()+'px';
    $('select-tax-area-id').style.display = "block";
    $('popup-shadow').style.display = "block";
    $('select-tax-area-button').observe('click', select_address);
        
    function select_address(){
        var tax_area_id="<?php echo $tax_area_id ?>";
        if (tax_area_id=="undefined" || tax_area_id.length==0) {
            alert('Please change  address');
            return false;
        }
       var new_city="<?php echo $new_city; ?>";
         
        $('select-tax-area-id').style.display = "none";
        $('popup-shadow').style.display = "none"; 
        
        var request = new Ajax.Request(
          '<?php echo Mage::getUrl('taxce/taxce/saveTaxArea');?>' ,
            {
               method:'post',
               onComplete: SelectAddressComplete,                  
               parameters: {tax_area_id:tax_area_id, new_city:new_city},
            }
        );  

       
    }    
    
     function SelectAddressComplete(){
         order.loadArea(['totals','shipping_address'], true, {} );     
    }
    
</script>