<?php $tax_area_responses = $this->getResponse(); ?>
<?php $tax_area_responses_array=$tax_area_responses->TaxAreaResponse->TaxAreaResult; ?> 
<div  class="selectaddress-container step a-item" >
    <div lass="col1-set">
        
            <h3><?php echo $this->__('Please verify your address'); ?></h3>          
            <ul class="form-list">
                 <li class="control"><?php echo $this->__('Your shipping address may be updated according to selection'); ?></li>
                 <?php foreach ($tax_area_responses_array as $tax_response): ?>                   
                    <li class="control">
                        <input type="radio" class="radio" id="tax_area_id_<?php echo $tax_response->taxAreaId; ?>"  value="<?php echo $tax_response->taxAreaId; ?>"   name="tax_area_id">
                        <?php
                            $tax_jurisdictions=$tax_response->Jurisdiction; 
                            krsort($tax_jurisdictions);                             
                            $area_names=array();
                            foreach ($tax_jurisdictions as $area_jursdiction )
                                $area_names[]=$area_jursdiction->_;
                      
                              $area_name=implode(', ', $area_names);                          
                        ?>
                        <label for="tax_area_id_<?php echo $tax_response->taxAreaId; ?>"><?php echo ucwords(strtolower($area_name)); ?></label>  
                        <input type="hidden" name="city_<?php echo $tax_response->taxAreaId; ?>" id="tax_city_<?php echo $tax_response->taxAreaId; ?>" value="<?php echo $tax_response->PostalAddress->City; ?>" />
                    </li>                    
                <?php endforeach; ?>
            </ul>
            <div class="buttons-set">
                <p class="required">&nbsp;</p>
                <button onclick="javascript:void(0);" class="button" type="button" id="select-tax-area-button"><span><span><?php echo $this->__('Continue'); ?></span></span></button>
            </div>    
    </div>  
</div>  
  
<script type="text/javascript">
    $("popup-shadow").style.height=$("html-body").getHeight()+'px';
    $('select-tax-area-id').style.display = "block";
    $('popup-shadow').style.display = "block";
    $('select-tax-area-button').observe('click', select_address);
        
    function select_address(){
        var tax_area_id=$$('input:checked[type="radio"][name="tax_area_id"]').pluck('value');
        if (tax_area_id=="undefined" || tax_area_id.length==0) {
            alert('Please select address');
            return false;
        }
        var new_city=$('tax_city_'+tax_area_id).value;
         
        $('select-tax-area-id').style.display = "none";
        $('popup-shadow').style.display = "none"; 
 
 
        var request = new Ajax.Request(
          '<?php echo Mage::getUrl('taxce/taxce/saveTaxArea');?>' ,
            {
               method:'post',
               onComplete: SelectAddressComplete,                  
               parameters: {tax_area_id:tax_area_id, new_city:new_city}
            }
        );  
       /* console.log(tax_area_id);  */       
    }    
    
    function SelectAddressComplete(){
         order.loadArea(['totals','shipping_address'], true, {} );     
    }
    
</script>