<?php 
/**
 * @package     VertexSMB_TaxCE
 * @license     http://opensource.org/licenses/OSL-3.0  The Open Software License 3.0 (OSL 3.0)
 * @author      Alex Lukyanau
 */
?>
<?php if (Mage::helper('taxce')->IsVertexSMBActive()): ?>
<style>
.address-window {z-index:9999; background: #fff; position:absolute; width:500px; height:auto; border: 1px solid #ccc; top: 55%; left:30%; display:none; }    
.selectaddress-container { margin:auto; padding: 25px;}
.selectaddress-container h3 {text-align:center;}
.selectaddress-container .form-list .control  label, .selectaddress-container .form-list .control  label:hover {background-color: #fff;}
.bg-shadow {z-index: 999; position: absolute; top: 0; width: 100%; height:100%; display:none; background-color: #000; opacity: 0.5;}
</style>    

<div id="select-tax-area-id" class="popup address-window">
    <div id="order-tax-area-load"></div> 
</div>
<div id="popup-shadow" class="bg-shadow">&nbsp;</div>
   <script type="text/javascript"> 
    
   
    order.loadArea= function(area, indicator, params){
        var url = this.loadBaseUrl;
        if (area) {
            area = this.prepareArea(area);
            url += 'block/' + area;
        }
        if (indicator === true) indicator = 'html-body';
        params = this.prepareParams(params);
        params.json = true;
        if (!this.loadingAreas) this.loadingAreas = [];
        
        if (indicator) {
            this.loadingAreas = area;
            
            new Ajax.Request(url, {
                parameters:params,
                loaderArea: indicator,
                onSuccess: function(transport) {
                    var response = transport.responseText.evalJSON();
                    this.loadAreaResponseHandler(response);
                     
                }.bind(this),
                
                onComplete:  function() {  
                          /*console.log(params['order[billing_address][city]']); */
                        if ( ( typeof area === 'string' &&  area!='header' && area!='totals' ) ||
                                ( typeof area === 'object' && area[0]!='totals' &&  area[0]!='header' )  || 
                                (typeof params['order[billing_address][city]']!='undefined' || typeof params['order[shipping_address][city]']!='undefined')  )  
                                           getTaxAreaId(params);                                      
                        }.bind(this),
                });
        }
        else {
            new Ajax.Request(url, {parameters:params,loaderArea: indicator, 
                onComplete: function() { 
                     
                           /* Add more handlers to update tax area depend of parameters shipping & billing*/             
                   if ( ( typeof area === 'string' &&  area!='header' && area!='totals' ) ||
                                ( typeof area === 'object' && area[0]!='totals' &&  area[0]!='header' ) ||
                                (typeof params['order[billing_address][city]']!='undefined' || typeof params['order[shipping_address][city]']!='undefined')  )  {                    
                         getTaxAreaId(params);                       
                    }
                }.bind(this) 
            });
          
           
        }
        if (typeof productConfigure != 'undefined' && area instanceof Array && area.indexOf('items') != -1) {
            productConfigure.clean('quote_items');
        }
    }
    
    
   function getTaxAreaId(params){      
       var request = new Ajax.Request(
                    '<?php echo Mage::getUrl('*/vertexSMB/TaxArea');?>' ,
                      {
                         method:'post',
                         /* onComplete: SelectAddressComplete, */
                         onSuccess: SelectAddressSucess,                   
                         parameters: params
                      }
                  );  
        
   }
    
   function SelectAddressSucess(transport){
      
         if (transport && transport.responseText){
            try{
                response = eval('(' + transport.responseText + ')');
            }
            catch (e) {
                response = {};
            }
        }

        if (response.error){
            if ((typeof response.message) == 'string') {         	     
            	alert(response.message);                
            } else {                                
                alert(response.message.join("\n"));                
            }

            return false;
        }
        if (response.message=='show_popup') {
        
            $('order-tax-area-load').update(response.html);
        
        } else {
           order.loadArea(['totals','shipping_address'], true, {} );
        }
         
   }
    
    
</script>
<?php endif; ?>